###
POST  http://localhost:5000/users/register
Content-Type: application/json

{
    "username":"Prita",
    "email":"pritamjitmanna1@gmail.com",
    "password":"password"
}


###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"pritamjitmanna@gmail.com",
    "password":"password"
}


###

GET http://localhost:5000/users/fetchuser
jwt_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjJmNjgxOTQ1N2JiMzBiYjAyY2MzMWU0In0sImR0IjoiYWRzcyIsImlhdCI6MTY2MDMyMjE5Nn0.odQPbla8xI2VFj36Fe6oaDM4PUp2-RJ94kZDhrsfuRY