###


# Register a user

POST  {{$dotenv HOST_URL}}:{{$dotenv PORT}}/users/register
Content-Type: application/json

{
    "username":"Prita",
    "email":"pritamjitmanna1@gmail.com",
    "password":"password"
}


###


# Login 

POST {{$dotenv HOST_URL}}:{{$dotenv PORT}}/users/login
Content-Type: application/json

{
    "email":"pritamjitmanna1@gmail.com",
    "password":"password"
}


###


# FetchUser Details

GET {{$dotenv HOST_URL}}:{{$dotenv PORT}}/users/fetchuser
jwt_token:{{$dotenv JWT_TOKEN}}


###


# Add Task

POST {{$dotenv HOST_URL}}:{{$dotenv PORT}}/tasks/addtask
Content-Type: application/json
jwt_token:{{$dotenv JWT_TOKEN}}

{
    "title":"My First Taskttee",
    "description":"I have to complete it",
    "DueDate":"2020-12-15"
}


###


# Update Task

PUT {{$dotenv HOST_URL}}:{{$dotenv PORT}}/tasks/updatetask/62f7cb0e831b554520cf860f
Content-Type: application/json
jwt_token:{{$dotenv JWT_TOKEN}}

{
    "title":"My First Task",
    "description":"I have to complete it jaldi",
    "DueDate":"2020-12-15"
}


###

# Delete A task

DELETE {{$dotenv HOST_URL}}:{{$dotenv PORT}}/tasks/deletetask/62f7cb0e831b554520cf860f
jwt_token:{{$dotenv JWT_TOKEN}}


###

# Fetch Tasks

GET {{$dotenv HOST_URL}}:{{$dotenv PORT}}/tasks/fetchtasks
jwt_token:{{$dotenv JWT_TOKEN}}


###

# Star a Task

PUT {{$dotenv HOST_URL}}:{{$dotenv PORT}}/tasks/startask/62fa685a5b16143a8171556f
Content-Length: 0
jwt_token:{{$dotenv JWT_TOKEN}}

###

# Task Completed

DELETE {{$dotenv HOST_URL}}:{{$dotenv PORT}}/tasks/taskcomplete/630c7ca11f7709f232daa030
jwt_token:{{$dotenv JWT_TOKEN}}

###

PUT {{$dotenv HOST_URL}}:{{$dotenv PORT}}/tasks/actioncount/
Content-Type: application/json
jwt_token:{{$dotenv JWT_TOKEN}}

{
    "operation":"deleted"
}
